name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - .github/workflows/deploy.yaml

jobs:
    lint-and-format:
        name: Lint and Format
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.13'

            - name: Install dependencies
              run: |
                  pip install -r backend/uv.lock

            - name: Run code qa with readme update
              uses: kgpl/gh-pylint@v1
              with:
                  python-version: 3.13
                  package-path: |
                    app
                    tests
                  requirements-path: backend/uv.lock
                  readme-path: README.md
                  fail-below: 7
            
            - name: Run tests with coverage
              run: |
                uv run pytest --cov
                  