name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - .github/workflows/ci_cd.yaml

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "backend/uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/pyproject.toml"

      - name: Install the project
        run: |
          cd backend
          uv sync --all-extras --dev

      - name: Run code qa
        run: |
          cd backend
          uv run pylint app tests --exit-zero

      - name: Run tests with coverage
        run: |
          cd backend
          uv run pytest --cov
            