name: Promote to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The Docker image tag to promote"
        required: true
        default: "latest"

jobs:
  promote-to-prod:
    name: Promote Image to Production
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_PROD_CREDENTIALS }}

      - name: Update Cloud Run with new image
        run: |
          gcloud run deploy ${{ vars.APP_NAME }} \
            --image ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROD_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY }}/${{ vars.APP_NAME }}:${{ github.event.inputs.tag }} \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
